# Control a motion-activated light.

blueprint:
  name: Motion-activated Light
  description: Turn on a light when motion is detected.
  domain: automation
  
  input:
    motion_entity:
      name: Motion Sensor Entity
      description: The motion sensor that controls the light.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    
    light_target:
      name: Light Target
      description: The target light to be controlled.
      selector:
        target:
          entity:
            domain: light
    
    no_motion_wait:
      name: Light Off Delay Time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

# If motion is detected within the delay, we restart.
mode: restart
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"

actions:
  
  # Turn on the light.
  - action: light.turn_on
    target: !input light_target
  
  # Wait for no motion detected.
  - wait_for_trigger:
      - trigger: state
        entity_id: !input motion_entity
        from: "on"
        to: "off"
  
  # Delay before turning off the light.
  - delay: !input no_motion_wait
  
  # Turn off the light.
  - action: light.turn_off
    target: !input light_target
