- id: '1608298913447'
  alias: Zone Notification
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.jon
      zone_entity: zone.home
      notify_device: a9570941d9dcebbd74ecb611f829a0f2
- id: '1628199776406'
  alias: Motion-activated Light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.guest_bath_motion_occupancy
      light_target:
        entity_id: light.guest_bath_light
- id: '1655124375247'
  alias: Kodi Test
  description: ''
  trigger:
  - platform: device
    device_id: 7000b71050bd8b00ed5ae05567e931c5
    domain: kodi
    entity_id: media_player.kodi
    type: turn_on
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lutron_dark
    metadata: {}
  mode: single
