#============================#
#     MQTT Room Presence     #
#============================#

- platform: mqtt
  name: Garage Espresense Sensor
  state_topic: espresense/rooms/garage/status
  json_attributes_topic: espresense/rooms/garage/telemetry
  payload_on: online
  payload_off: offline
  device_class: connectivity

- platform: mqtt
  name: House Espresense Sensor
  state_topic: espresense/rooms/house/status
  json_attributes_topic: espresense/rooms/house/telemetry
  payload_on: online
  payload_off: offline
  device_class: connectivity

#===================#
#     Legion PC     #
#===================#

- platform: mqtt
  name: "Legion T530 Connected"
  state_topic: "iotlink/workgroup/legion-t530/lwt"
  value_template: "{{ value }}"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "connectivity"
  qos: 1

#===============#
#     Dryer     #
#===============#

- platform: trend
  sensors:
    
    # Measures humidity falling by 40 over 22 minutes.
    dryer_humidity_falling:
      entity_id: sensor.dryer_humidity
      sample_duration: 1320   # 22m * 60s
      max_samples: 264        # 1320 / 5 (sampling interval)
      min_gradient: -0.03030  # -40 / 1200
    
    # Measures temperature falling by 20 over 8 minutes.
    dryer_temperature_falling:
      entity_id: sensor.dryer_temperature
      sample_duration: 480    # 8m * 60s
      max_samples: 96         # 480 / 5 (sampling interval)
      min_gradient: -0.04167  # -20 / 480
