#===============#
#     Dryer     #
#===============#

- platform: trend
  sensors:

    # Measures humidity falling by 30 over 25 minutes.
    # NOTE: The drop amount here must be kept in sync with the Register Dryer Event automation.
    dryer_humidity_falling:
      entity_id: sensor.dryer_humidity
      friendly_name: Dryer Humidity Falling
      sample_duration: 1500   # 25m * 60s
      max_samples: 330        # 1500 / 5 (sampling interval) + 10%
      min_gradient: -0.02000  # -30 / 1500

    # Measures temperature falling by 20 over 10 minutes.
    dryer_temperature_falling:
      entity_id: sensor.dryer_temperature
      friendly_name: Dryer Temperature Falling
      sample_duration: 600    # 10m * 60s
      max_samples: 132        # 600 / 5 (sampling interval) + 10%
      min_gradient: -0.03333  # -20 / 600

#=================#
#     Driving     #
#=================#

- platform: bayesian
  name: Jon Driving
  unique_id: jon_driving
  prior: 0.2
  probability_threshold : 0.8
  
  observations:
    - platform: state
      entity_id: binary_sensor.jon_companion_driving
      to_state: 'on'
      prob_given_true: 0.9
      prob_given_false: 0.1

    - platform: numeric_state
      entity_id: sensor.home_jon_distance
      above: 200
      prob_given_true: 0.9
      prob_given_false: 0.1

    - platform: state
      entity_id: sensor.jon_galaxy_detected_activity
      to_state: 'in-vehicle'
      prob_given_true: 0.5
      prob_given_false: 0.1
