#===============#
#     Dryer     #
#===============#

- platform: trend
  sensors:
    
    # Measures humidity falling by 40 over 25 minutes.
    dryer_humidity_falling:
      entity_id: sensor.dryer_humidity
      sample_duration: 1500   # 25m * 60s
      max_samples: 300        # 1500 / 5 (sampling interval)
      min_gradient: -0.02667  # -40 / 1500
    
    # Measures temperature falling by 20 over 8 minutes.
    dryer_temperature_falling:
      entity_id: sensor.dryer_temperature
      sample_duration: 480    # 8m * 60s
      max_samples: 96         # 480 / 5 (sampling interval)
      min_gradient: -0.04167  # -20 / 480
