#======================#
#     Garage Doors     #
#======================#

- platform: template
  covers:
    
    garage_door_north:
      device_class: garage
      friendly_name: 'Garage Door North'
      value_template: >
        {% if is_state('binary_sensor.shelly1_garage_north_contact', 'on') %}
          closed
        {% else %}
          open
        {% endif %}
      open_cover:
        service: switch.turn_on
        entity_id: switch.shelly1_garage_north
      close_cover:
        service: switch.turn_on
        entity_id: switch.shelly1_garage_north
      stop_cover:
        service: switch.turn_on
        entity_id: switch.shelly1_garage_north
    
    garage_door_south:
      device_class: garage
      friendly_name: 'Garage Door South'
      value_template: >
        {% if is_state('binary_sensor.shelly1_garage_south_contact', 'on') %}
          closed
        {% else %}
          open
        {% endif %}
      open_cover:
        service: switch.turn_on
        entity_id: switch.shelly1_garage_south
      close_cover:
        service: switch.turn_on
        entity_id: switch.shelly1_garage_south
      stop_cover:
        service: switch.turn_on
        entity_id: switch.shelly1_garage_south
