#========================#
#     Light Switches     #
#========================#

# Change switches (controlling lights) to lights
#
# NOTE: This does not include temporary lights such as Christmas lights.
- platform: switch
  name: Attic Light
  entity_id: switch.attic_light

- platform: switch
  name: Dining Room Hutch
  entity_id: switch.dining_room_hutch

- platform: switch
  name: Dining Room Lamps
  entity_id: switch.dining_room_lamps

- platform: switch
  name: Driveway Lights
  entity_id: switch.driveway_lights

- platform: switch
  name: Foyer Hutch
  entity_id: switch.foyer_hutch

- platform: switch
  name: Front Floodlight
  entity_id: switch.front_floodlight

- platform: switch
  name: Garage Lights
  entity_id: switch.garage_lights

- platform: switch
  name: Guest Bath Light
  entity_id: switch.guest_bath_light

- platform: switch
  name: Guest Bedroom Lamp
  entity_id: switch.guest_bedroom_lamp

- platform: switch
  name: Guest Bedroom Lamp 2
  entity_id: switch.guest_bedroom_lamp_2

- platform: switch
  name: Hallway Lamp
  entity_id: switch.hallway_lamp

- platform: switch
  name: Laundry Room Light
  entity_id: switch.laundry_room_light

- platform: switch
  name: Master Bath Light
  entity_id: switch.master_bath_light

- platform: switch
  name: Porch Light
  entity_id: switch.porch_light

- platform: switch
  name: Snack Light
  entity_id: switch.snack_light

- platform: switch
  name: Stairway Light
  entity_id: switch.stairway_light

- platform: switch
  name: Upstairs Bedroom Light
  entity_id: switch.upstairs_bedroom_light

- platform: switch
  name: Upstairs Hallway Lights
  entity_id: switch.upstairs_hallway_lights

- platform: switch
  name: Utility Light
  entity_id: switch.utility_light