#==================================#
#     Lovelace Admin Dashboard     #
#==================================#

# Include templates
button_card_templates:
  !include /config/lovelace/button_card_templates.yaml

decluttering_templates:
  !include /config/lovelace/decluttering_templates.yaml

# Each view in its own file
title: Overview
views:
  - !include /config/lovelace/dash_overview/views/home.yaml
  - !include /config/lovelace/dash_overview/views/lighting.yaml
  - !include /config/lovelace/dash_overview/views/environment.yaml
  - !include /config/lovelace/dash_overview/views/energy.yaml
  - !include /config/lovelace/dash_overview/views/health.yaml
  - !include /config/lovelace/dash_overview/views/theater.yaml
  - !include /config/lovelace/dash_overview/views/office.yaml
  - !include /config/lovelace/dash_overview/views/devices.yaml
  - !include /config/lovelace/dash_overview/views/levels.yaml
  - !include /config/lovelace/dash_overview/views/monitoring.yaml
  - !include /config/lovelace/dash_overview/views/controls.yaml
  - !include /config/lovelace/dash_overview/views/tracking.yaml
  
  # NOTE: The following two tabs are invisible, and are shown in the sidebar instead. The definitions
  # are needed to provide a URL for the sidebar items.
  - !include /config/lovelace/dash_overview/views/first_floor.yaml
  - !include /config/lovelace/dash_overview/views/second_floor.yaml