#=========================#
#     Epson projector     #
#=========================#

# This uses the custom component epson_projector.
- platform: epson_projector
  name: Epson Projector
  host: !secret projector_ip_addr
  password: !secret epson_password

#==========================#
#     Nvidia Shield TV     #
#==========================#

# NOTE: The app names used here must match those defined in automation/media_player.yaml for the initialize_*_volume automations.

- platform: androidtv
  name: Shield TV
  host: !secret shield_ip_addr
  apps:
    com.amazon.amazonvideo.livingroom:      'Amazon Prime'
    com.disney.disneyplus:                  'Disney+'
    com.espn.score_center:                  'ESPN'
    com.hbo.hbonow:                         'HBO Max'
    org.xbmc.kodi:                          'Kodi'
   #com.netflix.ninja:                      'Netflix'  # built-in
    com.pandora.android.atv:                'Pandora'
    com.cbs.ott:                            'Paramount+'
    com.peacocktv.peacockandroid:           'Peacock'
    com.google.android.youtube.tvunplugged: 'Youtube TV'
  exclude_unnamed_apps: true
    
  # Set the paused/playing state for apps that use media_session_state. Default to standby state
  # if not paused or playing.
  #
  # Special cases:
  #
  # - Some apps don't use media_session_state (it's always "none"), so we can't tell if 
  #   something is playing or paused, so just use standby state.
  # - For Pandora we don't want total darkness. Just use standby state, and dim lighting is turned on in 
  #   the volume setting automation for Pandora.
  state_detection_rules:
    'com.google.android.tvlauncher':
      - 'standby'
    
    'com.amazon.amazonvideo.livingroom':
      - 'paused':
          'media_session_state': 2
      - 'playing':
          'media_session_state': 3
      - 'standby'
    
    'com.disney.disneyplus':
      - 'paused':
          'media_session_state': 2
      - 'playing':
          'media_session_state': 3
      - 'standby'
    
    # Looks like this URL is not right, but I can't find the real one.
    'com.espn.score_center':
      - 'paused':
          'media_session_state': 2
      - 'playing':
          'media_session_state': 3
      - 'standby'
    
    'com.hbo.hbonow':
      - 'paused':
          'media_session_state': 2
      - 'playing':
          'media_session_state': 3
      - 'standby'
    
    'org.xbmc.kodi':
      - 'paused':
          'media_session_state': 2
      - 'playing':
          'media_session_state': 3
      - 'standby'
    
    'com.netflix.ninja':
      - 'paused':
          'media_session_state': 2
      - 'playing':
          'media_session_state': 3
      - 'standby'
    
    'com.pandora.android.atv':
      - 'standby'
    
    # CBS was rebranded as Paramount Plus.
    'com.cbs.ott':
      - 'paused':
          'media_session_state': 2
      - 'playing':
          'media_session_state': 3
      - 'standby'
    
    'com.peacocktv.peacockandroid':
      - 'standby'
      
    'com.google.android.youtube.tvunplugged':
      - 'paused':
          'media_session_state': 2
      - 'playing':
          'media_session_state': 3
      - 'standby'