# Initialize the receiver volume based on the Harmony device in use.
# The volume to use is set by the UI into a number for each device. We use a default of 60% if we
# can't extract the volume from the number.

blueprint:
  name: Harmony Device Volume Initializer
  description: Initialize the volume for a Harmony device.
  domain: automation
  
  input:
    device_name:
      name: Harmony Device Name
      description: The name of the Harmony device, for example 'BD Player'.

# The !input tag cannot be used in templates, so assign variables to any needed inputs.
variables:
  input_device_name: !input device_name
  
  selected_device: "{{ input_device_name.replace(' ', '_') | lower }}"
  selected_device_volume: "{{ states('input_number.' ~ selected_device ~ '_volume') | float(0.60) }}"

triggers:
  - trigger: state
    entity_id: sensor.harmony_hub
    to: !input device_name

actions:
  - action: script.set_receiver_volume
    data:
      target_name: "{{ input_device_name }}"
      volume: "{{ selected_device_volume }}"
