# Initialize the receiver volume based on the Harmony device in use.
# The device name and volume are inputs.

blueprint:
  name: Harmony Device Volume Initializer
  description: Initialize the volume for a Harmony device.
  domain: automation
  
  input:
    device_name:
      name: Harmony Device Name
      description: The name of the Harmony device, for example 'BD Player'.
    
    volume:
      name: Volume Level
      description: The volume level as a percentage, for example 0.61 for 61%.
      selector:
        number:  # This is the minimum and maximum volume currently supported ... coordinate with automations in theater.yaml
          min: 0.48
          max: 0.64
          mode: slider

variables:
  input_device_name: !input device_name
  input_volume: !input volume

trigger:
  - platform: state
    entity_id: sensor.harmony_hub
    to: !input device_name

action:
  - service: system_log.write
    data:
      message: "Setting volume for {{ input_device_name }} to {{ input_volume }}"
      level: debug
  
  - service: media_player.volume_set
    data:
      entity_id: media_player.marantz_sr7012
      volume_level: "{{ input_volume | float(0) }}"
