# Initialize the receiver volume based on the Shield TV application in use.
# The volume to use is set by the UI into a number for each application. We use a default of 60% if we
# can't extract the volume from the number.

blueprint:
  name: Shield App Volume Initializer
  description: Initialize the volume for a Shield TV application.
  domain: automation
  
  input:
    appl_name:
      name: Shield Application Name
      description: The name of the application on the Shield TV, for example 'Youtube TV'.
  
trace:
  stored_traces: 20

variables:
  input_appl_name: !input appl_name
  
  selected_app: "{{ input_appl_name.replace('+', ' plus').replace(' ', '_') | lower }}"
  selected_app_volume: "{{ states('input_number.' ~ selected_app ~ '_volume') | float(0.60) }}"

trigger:
  - platform: state
    entity_id: media_player.shield_tv
    attribute: app_name
    to: !input appl_name

# Weed out spurious broken pipe errors, which for some odd reason show up in the app name.
condition: "{{ trigger.from_state.attributes.app_name is defined and 'Broken pipe' not in trigger.from_state.attributes.app_name }}"

action:
  - service: script.set_receiver_volume
    data:
      appl_name: "{{ input_appl_name }}"
      volume: "{{ selected_app_volume }}"
