# Initialize the receiver volume based on the Shield TV application in use.
# The application name and volume are inputs.

blueprint:
  name: Shield App Volume Initializer
  description: Initialize the volume for a Shield TV application.
  domain: automation
  
  input:
    appl_name:
      name: Shield Application Name
      description: The name of the application on the Shield TV, for example 'Youtube TV'.
    
    volume:
      name: Volume Level
      description: The volume level as a percentage, for example 0.61 for 61%.
      selector:
        number:  # This is the minimum and maximum volume currently supported ... coordinate with automations in theater.yaml
          min: 0.48
          max: 0.64
          mode: slider
  
trace:
  stored_traces: 20

variables:
  input_appl_name: !input appl_name
  input_volume: !input volume

trigger:
  - platform: state
    entity_id: media_player.shield_tv
    attribute: app_name
    to: !input appl_name

# Weed out spurious broken pipe errors, which for some odd reason show up in the app name.
condition: "{{ trigger.from_state.attributes.app_name is defined and 'Broken pipe' not in trigger.from_state.attributes.app_name }}"

action:
  - service: system_log.write
    data:
      message: "Setting volume for {{ input_appl_name }} to {{ input_volume }}"
      level: debug
  
  - service: media_player.volume_set
    data:
      entity_id: media_player.marantz_sr7012
      volume_level: "{{ input_volume | float(0) }}"
