# Clear a maintenance below notification from my mobile device.

blueprint:
  name: Maintenance Below Notification Clear
  description: Clear a maintenance below notification from my mobile device.
  domain: automation
  
  input:
    sensor_entity:
      name: Sensor Entity
      description: Sensor entity to check.
      selector:
        entity:
          domain: sensor

    threshold:
      name: Threshold
      description: Threshold value. Note that the value must rise ABOVE this threshold, since the original notification was below it.
    
    tag:
      name: Tag
      description: Tag to use to clear the notification.

# Allow for multiple simultaneous changes. Might be unnecessary, but it doesn't hurt.
mode: queued
  
# Trigger when the state of the sensor rises above the input threshold.
trigger:
  - platform: numeric_state
    entity_id: !input sensor_entity
    above: !input threshold

# Weed out junk.
condition: "{{ trigger.from_state.state not in ['unknown', 'unavailable'] }}"

action:
  - service: notify.mobile_app_jon_galaxy
    data:
      message: 'clear_notification'
      data:
        tag: !input tag
