#=========================#
#     Environment Tab     #
#=========================#

title: Environment
icon: mdi:thermometer
panel: true
cards:
  - type: custom:layout-card
    layout_type: custom:vertical-layout
    cards:
      - !include /config/lovelace/dash_overview/cards/environment/thermostat.yaml
      - type: custom:layout-break
      - !include /config/lovelace/dash_overview/cards/environment/hvac_vents.yaml
      
      - type: custom:layout-break
      - type: custom:stack-in-card
        title: Area Temperatures
        cards:
          - !include /config/lovelace/dash_overview/cards/environment/areas_environment.yaml
          - !include /config/lovelace/dash_overview/cards/environment/areas_environment_2.yaml
          - !include /config/lovelace/dash_overview/cards/environment/min_max_temps.yaml
