# DHT22 temperature and humidity sensor
sensor:
  - platform: dht
    pin: D2
    model: DHT22
    update_interval: $window_interval
    temperature:
      name: Temperature
      unit_of_measurement: "°F"
      filters:
        - calibrate_linear:
            # Map 0.0 (from sensor) to 0.0 (true value)
            - 0.0 -> 0.0
            - $calibrate_measured -> $calibrate_truth
        - lambda: return x * (9.0/5.0) + 32.0;
        - sliding_window_moving_average:
            window_size: $window_size
            send_every:  $window_size
    humidity:
      name: Humidity
      filters:
        - sliding_window_moving_average:
            window_size: $window_size
            send_every:  $window_size
