# Core configuration for a Sonoff S31 plug
esphome:
  name: $device_name
  friendly_name: $friendly_name

esp8266:
  board: esp12e
  early_pin_init: false
  #restore_from_flash: false # Set false if flashing using a programmer
  restore_from_flash: true # Set true if flashing using OTA

# Enable logging
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
  logs:
    sensor: DEBUG # (Overide any global setting, to VERBOSE will spamming the cse7766 sensors)
