# Core configuration for an ESP32 board
esphome:
  name: $device_name
  friendly_name: $friendly_name

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

# Enable logging
logger:
  level: $loglevel
