# Adafruit TSL2591 ambient light sensor
sensor:
  - platform: tsl2591
    integration_time: 600ms
    gain: ${gain}
    update_interval: $window_interval
    power_save_mode: false
    visible:
      name: Ambient Light
      unit_of_measurement: lux
      filters:
        - filter_out: 65535
