# Enable do not disturb on an Amazon Echo media player.

blueprint:
  name: Echo Do Not Disturb
  description: Enable do not disturb on an Amazon Echo media player.
  domain: script
  
  input:
    switch_entity:
      name: Target Echo Do Not Disturb Switch
      description: Echo media player switch to enable do not disturb.
      selector:
        entity:
          domain: switch

sequence:
  - variables:
      echo_name: "{{ state_attr(switch_entity, 'friendly_name') | replace(' do not disturb switch', '') }}"
    
  # Simulate the request if testing mode is on.
  - if:
      - "{{ is_state('input_boolean.testing_mode', 'off') }}"
      
    then:
      - service: switch.turn_on
        entity_id: !input switch_entity
      
    else:
      - service: script.log_testing_simulation
        data:
          category: echo
          message: "{{ 'Echo name ' ~ echo_name ~ ' muted.' }}"
