# Enable do not disturb on an Amazon Echo media player.

blueprint:
  name: Echo Do Not Disturb
  description: Enable do not disturb on an Amazon Echo media player.
  domain: script
  
  input:
    switch_entity:
      name: Target Echo Do Not Disturb Switch
      description: Echo media player switch to enable do not disturb.
      selector:
        entity:
          domain: switch
    
    mute_duration:
      name: Do Not Disturb Duration
      description: Entity that contains the do not disturb duration in seconds.

sequence:
  - service: switch.turn_on
    entity_id: !input switch_entity
  
  - delay:
      seconds: !input mute_duration
  
  - service: switch.turn_off
    entity_id: !input switch_entity
