# Operate a garage door.

blueprint:
  name: Garage Door Operation
  description: Open or close a garage door, with an optional informational message, and confirmation detection.
  domain: script
  
  input:
    name:
      name: Garage Door Name
      description: 'The garage door user friendly name.'
    
    operation:
      name: Garage Door Operation
      description: 'Whether to open or close the door.'
      selector:
        select:
          options:
            - Open
            - Close
    
    contact:
      name: Contact Sensor Entity
      description: 'The garage door contact sensor entity.'
      selector:
        entity:
          domain: binary_sensor
    
    switch:
      name: Switch Entity
      description: 'The switch to operate the garage door.'
      selector:
        entity:
          domain: switch

mode: parallel
  
# NOTE: these are variables passed through scripts that use this blueprint. They are not referenced at all in those
# scripts, but instead are specified by any automations/scripts that call those scripts.
fields:
  use_info_message:
    name: Use Informational Message
    description: Should an informational notification message be issued prior to operating the door?
    selector:
      boolean:

# The !input tag cannot be used in templates, so assign variables to the necessary inputs.
variables:
  input_name: !input name
  input_operation: !input operation
  input_contact: !input contact
  
  lockout_timer: "{{ 'timer.garage_door_' ~ input_name ~ '_lockout' }}"  
  msg_operation: "{{ iif(input_operation == 'Open', 'Opening', 'Closing') }}"  
  message_tag: "{{ input_name | lower }}_garage_door_operation"
  error_tag: "{{ input_name | lower }}_garage_door_problem"

sequence:
      
  # Action is only required if the door is currently in the opposite state (contact on means closed).
  - condition: "{{ iif(input_operation == 'Open', is_state(input_contact, 'on'), is_state(input_contact, 'off')) }}"
  
  # Prevent multiple quick actions, for example trying to open the door twice because I arrived home at the same time as a 
  # family member. Such rapid actions leave the door partially open. We use a timer for this purpose.
  - condition: "{{ states(lockout_timer) == 'idle' }}"
    
  # Send an informational notification that the door is about to be operated, if requested.
  - if:
      - "{{ use_info_message == true }}"
      
    then:
          
      # Register the tag.
      - action: script.register_mobile_notification
        data:
          tag: "{{ message_tag }}"
          clear_type: auto
          title: 'Attention:'
          message: '{{ msg_operation }} garage door {{ input_name }}.'
          channel: standard
          timeout: 0
      
      # Send the informational notification.
      - action: script.send_notification
        data:
          destination:
            - mobile
          title: 'Attention:'
          message: '{{ msg_operation }} garage door {{ input_name }}.'
          channel: standard
          tag: "{{ message_tag }}"
          timeout: 0
    
  # Operate the door.
  - action: switch.turn_on
    target:
      entity_id: !input switch
    
  # Wait a bit before confirming.
  - delay: '00:00:15'
    
  # If the door is in the proper state, delay a bit before removing the first notification (if needed).
  - if: 
      - "{{ iif(input_operation == 'Open', is_state(input_contact, 'off'), is_state(input_contact, 'on')) }}"
    
    then:
      - delay: "{{ iif(use_info_message == true, '00:15:00', 0) }}"
    
    # The operation did not succeed, so send a more important one.
    else:
          
      # Register the tag.
      - action: script.register_mobile_notification
        data:
          tag: "{{ error_tag }}"
          clear_type: manual
          title: 'Warning:'
          message: 'Garage door {{ input_name }} operation did not succeed.'
          channel: critical
          timeout: 0
      
      # Send the new notification.
      - action: script.send_notification
        data:
          destination:
            - mobile
          title: 'Warning:'
          message: 'Garage door {{ input_name }} operation did not succeed.'
          channel: critical
          tag: "{{ error_tag }}"
          timeout: 0
  
  - if:
      - "{{ use_info_message == true }}"
      
    then:

      # Remove the first notification and unregister the tag.
      - action: script.remove_mobile_notification
        data:
          tag: "{{ message_tag }}"
