#============================#
#     MQTT Room Presence     #
#============================#

# Blue Charm beacon state sensor, updated via ESPresence scanners.
- platform: mqtt_room
  device_id: 'iBeacon:426c7565-4368-6172-6d42-6561636f6e73-3838-4949'
  name: 'Blue Charm Beacon'
  state_topic: 'espresense/devices/iBeacon:426c7565-4368-6172-6d42-6561636f6e73-3838-4949'
  timeout: 60
  away_timeout: 120

# Nut Mini state sensor, updated via ESPresence scanners.
- platform: mqtt_room
  device_id: 'nut:c8d12a58fc78'
  name: 'Nut Mini'
  state_topic: 'espresense/devices/nut:c8d12a58fc78'
  timeout: 60
  away_timeout: 120
