#===========================#
#     Health Statistics     #
#===========================#

#=== CPAP AHI average

- platform: statistics
  name: AHI Average
  unique_id: ahi_average
  entity_id: sensor.cpap_ahi_events_per_hour
  state_characteristic: average_timeless
  max_age:
    days: 30
