#=======================#
#     Date And Time     #
#=======================#

- platform: time_date
  display_options:
    - 'date'
    - 'time'

#======================#
#     Raspberry Pi     #
#======================#.

# Last boot time, disk, memory & CPU usage
- platform: systemmonitor
  resources:
    - type: last_boot
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use

#================#
#     Hockey     #
#================#

# Next Canes Game
- platform: rest
  name: Next Canes Game
  scan_interval: 31536000
  json_attributes_path: "$.games[0]"
  json_attributes:
    - startTimeUTC
    - awayTeam
    - homeTeam
  resource_template: https://api-web.nhle.com/v1/club-schedule/CAR/week/{{ now().strftime('%Y-%m-%d') }}
  value_template: >   
    {% if value_json is defined and value_json | length and value_json.games[0].startTimeUTC is defined %}
      {{ as_timestamp(value_json.games[0].startTimeUTC) | timestamp_custom('%b %d %I:%M%p') }}
    {% else %}
      {{ as_timestamp(now().today() + timedelta(days = 5)) | timestamp_custom('%b %d %I:%M%p') }}
    {% endif %}

# Next Flyers Game
- platform: rest
  name: Next Flyers Game
  scan_interval: 31536000
  json_attributes_path: "$.games[0]"
  json_attributes:
    - startTimeUTC
    - awayTeam
    - homeTeam
  resource_template: https://api-web.nhle.com/v1/club-schedule/PHI/week/{{ now().strftime('%Y-%m-%d') }}
  value_template: >   
    {% if value_json is defined and value_json | length and value_json.games[0].startTimeUTC is defined %}
      {{ as_timestamp(value_json.games[0].startTimeUTC) | timestamp_custom('%b %d %I:%M%p') }}
    {% else %}
      {{ as_timestamp(now().today() + timedelta(days = 5)) | timestamp_custom('%b %d %I:%M%p') }}
    {% endif %}

#=======================#
#     Unifi Counter     #
#=======================#

- platform: unifics
  name: Unifi Counter
  host: !secret unifi_host
  username: !secret unifi_username
  password: !secret unifi_password
  udm: True

#====================#
#     Gas Prices     #
#====================#

- platform: rest
  name: Gas Search Siler City
  unique_id: gas_search_siler_city
  icon: mdi:gas-station
  scan_interval: 3600
  resource: https://www.gasbuddy.com/graphql
  method: POST
  headers:
    Content-Type: application/json
  payload: >
    {
      "operationName": "LocationBySearchTerm",
      "variables": {
          "maxAge": 0,
          "search": "27344"
      },
      "query": "query LocationBySearchTerm($brandId: Int, $cursor: String, $maxAge: Int, $search: String) { locationBySearchTerm(search: $search) { stations(brandId: $brandId, cursor: $cursor, maxAge: $maxAge) { count cursor { next } results {  address { country line1 line2 locality postalCode region }  fuels id name prices { cash { nickname postedTime price } credit { nickname postedTime price } } } } trends { areaName country today todayLow trend } }}"
    }
  state_class: measurement
  value_template: "{{ value_json.data.locationBySearchTerm.trends.0.today }}"
  json_attributes_path: "$.data.locationBySearchTerm"
  json_attributes:
    - stations
    - trends

- platform: rest
  name: Gas Search Pittsboro
  unique_id: gas_search_pittsboro
  icon: mdi:gas-station
  scan_interval: 3600
  resource: https://www.gasbuddy.com/graphql
  method: POST
  headers:
    Content-Type: application/json
  payload: >
    {
      "operationName": "LocationBySearchTerm",
      "variables": {
          "maxAge": 0,
          "search": "27312"
      },
      "query": "query LocationBySearchTerm($brandId: Int, $cursor: String, $maxAge: Int, $search: String) { locationBySearchTerm(search: $search) { stations(brandId: $brandId, cursor: $cursor, maxAge: $maxAge) { count cursor { next } results {  address { country line1 line2 locality postalCode region }  fuels id name prices { cash { nickname postedTime price } credit { nickname postedTime price } } } } trends { areaName country today todayLow trend } }}"
    }
  state_class: measurement
  value_template: "{{ value_json.data.locationBySearchTerm.trends.0.today }}"
  json_attributes_path: "$.data.locationBySearchTerm"
  json_attributes:
    - stations
    - trends
