#================#
#     Hockey     #
#================#

# Next Canes Game
- platform: rest
  name: Next Canes Game
  scan_interval: 31536000
  json_attributes_path: "$.games[0]"
  json_attributes:
    - startTimeUTC
    - awayTeam
    - homeTeam
    - tvBroadcasts
  resource_template: https://api-web.nhle.com/v1/club-schedule/CAR/week/{{ now().strftime('%Y-%m-%d') }}
  value_template: >
    {% if value_json is defined and value_json | length and value_json.games is defined and value_json.games | length and value_json.games[0].startTimeUTC is defined %}
      {{ as_timestamp(value_json.games[0].startTimeUTC) | timestamp_custom('%b %d %I:%M%p') }}
    {% else %}
      {{ as_timestamp(now().today() + timedelta(days = 5)) | timestamp_custom('%b %d %I:%M%p') }}
    {% endif %}

# Next Flyers Game
- platform: rest
  name: Next Flyers Game
  scan_interval: 31536000
  json_attributes_path: "$.games[0]"
  json_attributes:
    - startTimeUTC
    - awayTeam
    - homeTeam
  resource_template: https://api-web.nhle.com/v1/club-schedule/PHI/week/{{ now().strftime('%Y-%m-%d') }}
  value_template: > 
    {% if value_json is defined and value_json | length and value_json.games is defined and value_json.games | length and value_json.games[0].startTimeUTC is defined %}
      {{ as_timestamp(value_json.games[0].startTimeUTC) | timestamp_custom('%b %d %I:%M%p') }}
    {% else %}
      {{ as_timestamp(now().today() + timedelta(days = 5)) | timestamp_custom('%b %d %I:%M%p') }}
    {% endif %}
