#=======================#
#     Date And Time     #
#=======================#

- platform: time_date
  display_options:
    - 'date'
    - 'time'

#==============#
#     Moon     #
#==============#

- platform: moon

#======================#
#     Raspberry Pi     #
#======================#

# CPU temperature
- platform: command_line
  name: CPU Temp
  unit_of_measurement: '°'
  command: 'cat /sys/class/thermal/thermal_zone0/temp'
  value_template: "{{ (value | multiply(0.001) | float(0)) | round(2) }}"

# Last boot time, disk, memory & CPU usage
- platform: systemmonitor
  resources:
    - type: last_boot
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use

#========================#
#     System Up Time     #
#========================#

# System up time
- platform: uptime
