#=======================#
#     Date And Time     #
#=======================#

- platform: time_date
  display_options:
    - 'date'
    - 'time'

#==============#
#     Moon     #
#==============#

- platform: moon

#====================#
#     Supervisor     #
#====================#

# Sensor to track available updates for supervisor & addons
- platform: command_line
  name: Supervisor updates
  command: 'curl http://supervisor/supervisor/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version,"update_available":.data.update_available,"addons":[.data.addons[] | select(.update_available)]}'''
  value_template: "{{ value_json.addons | length }}"
  unit_of_measurement: pending update(s)
  json_attributes:
  - update_available
  - newest_version
  - current_version
  - addons

#======================#
#     Raspberry Pi     #
#======================#

# CPU temperature
- platform: command_line
  name: CPU Temp
  unit_of_measurement: '°'
  command: 'cat /sys/class/thermal/thermal_zone0/temp'
  value_template: "{{ (value | multiply(0.001) | float(0)) | round(2) }}"

# Last boot time, disk, memory & CPU usage
- platform: systemmonitor
  resources:
    - type: last_boot
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use

#========================#
#     System Up Time     #
#========================#

# System up time
- platform: uptime