#=================================================#
#     Reimann Integrations - Calculated Power     #
#=================================================#

#------------------#
#   -- Lights --   #
#------------------#

# Attic Light
- platform: integration
  name: attic_light_energy
  source: sensor.attic_light_power
  unit_prefix: k
  round: 2

# Dining Room Hutch
- platform: integration
  name: dining_room_hutch_energy
  source: sensor.dining_room_hutch_power
  unit_prefix: k
  round: 2

# Dining Room Lamps
- platform: integration
  name: dining_room_lamps_energy
  source: sensor.dining_room_lamps_power
  unit_prefix: k
  round: 2

# Driveway Lights
- platform: integration
  name: driveway_lights_energy
  source: sensor.driveway_lights_power
  unit_prefix: k
  round: 2

# Fire TV
- platform: integration
  name: fire_tv_energy
  source: sensor.fire_tv_power
  unit_prefix: k
  round: 2

# Floor Fan
- platform: integration
  name: floor_fan_energy
  source: sensor.floor_fan_power
  unit_prefix: k
  round: 2

# Foyer Hutch
- platform: integration
  name: foyer_hutch_energy
  source: sensor.foyer_hutch_power
  unit_prefix: k
  round: 2

# Front Floodlight
- platform: integration
  name: front_floodlight_energy
  source: sensor.front_floodlight_power
  unit_prefix: k
  round: 2

# Garage Lights
- platform: integration
  name: garage_lights_energy
  source: sensor.garage_lights_power
  unit_prefix: k
  round: 2

# Guest Bath Fan
- platform: integration
  name: guest_bath_fan_energy
  source: sensor.guest_bath_fan_power
  unit_prefix: k
  round: 2

# Guest Bath Light
- platform: integration
  name: guest_bath_light_energy
  source: sensor.guest_bath_light_power
  unit_prefix: k
  round: 2

# Guest Bedroom Lamp
- platform: integration
  name: guest_bedroom_lamp_energy
  source: sensor.guest_bedroom_lamp_power
  unit_prefix: k
  round: 2

# Guest Bedroom Lamp 2
- platform: integration
  name: guest_bedroom_lamp_2_energy
  source: sensor.guest_bedroom_lamp_2_power
  unit_prefix: k
  round: 2

# Hallway Lamp
- platform: integration
  name: hallway_lamp_energy
  source: sensor.hallway_lamp_power
  unit_prefix: k
  round: 2

# Laundry Room Light
- platform: integration
  name: laundry_room_light_energy
  source: sensor.laundry_room_light_power
  unit_prefix: k
  round: 2

# Master Bath Fan
- platform: integration
  name: master_bath_fan_energy
  source: sensor.master_bath_fan_power
  unit_prefix: k
  round: 2

# Master Bath Light
- platform: integration
  name: master_bath_light_energy
  source: sensor.master_bath_light_power
  unit_prefix: k
  round: 2

# Office Bookcase Light
- platform: integration
  name: office_bookcase_light_energy
  source: sensor.office_bookcase_light_power
  unit_prefix: k
  round: 2

# Porch Light
- platform: integration
  name: porch_light_energy
  source: sensor.porch_light_power
  unit_prefix: k
  round: 2

# Snack Light
- platform: integration
  name: snack_light_energy
  source: sensor.snack_light_power
  unit_prefix: k
  round: 2

# Stairway Light
- platform: integration
  name: stairway_light_energy
  source: sensor.stairway_light_power
  unit_prefix: k
  round: 2

# Theater Ceiling
- platform: integration
  name: theater_ceiling_energy
  source: sensor.theater_ceiling_power
  unit_prefix: k
  round: 2

# Theater Sconces
- platform: integration
  name: theater_sconces_energy
  source: sensor.theater_sconces_power
  unit_prefix: k
  round: 2

# Upstairs Bedroom Light
- platform: integration
  name: upstairs_bedroom_light_energy
  source: sensor.upstairs_bedroom_light_power
  unit_prefix: k
  round: 2

# Upstairs Bedroom Outlet
- platform: integration
  name: upstairs_bedroom_outlet_energy
  source: sensor.upstairs_bedroom_outlet_power
  unit_prefix: k
  round: 2

# Upstairs Hallway Lights
- platform: integration
  name: upstairs_hallway_lights_energy
  source: sensor.upstairs_hallway_lights_power
  unit_prefix: k
  round: 2

# Utility Light
- platform: integration
  name: utility_light_energy
  source: sensor.utility_light_power
  unit_prefix: k
  round: 2

#-------------------#
#   -- Devices --   #
#-------------------#

# Projector
- platform: integration
  name: projector_energy
  source: sensor.projector_power
  unit_prefix: k
  round: 2

# Receiver
- platform: integration
  name: receiver_energy
  source: sensor.receiver_power
  unit_prefix: k
  round: 2

# Shield TV
- platform: integration
  name: shield_tv_energy
  source: sensor.shield_tv_power
  unit_prefix: k
  round: 2

#===============================================#
#     Reimann Integrations - Measured Power     #
#===============================================#

#------------------#
#   -- Lights --   #
#------------------#

# Family Room Lamp
- platform: integration
  name: family_room_lamp_energy
  source: sensor.family_room_lamp_current_consumption
  unit_prefix: k
  round: 2

# Master Bedroom Lamp
- platform: integration
  name: master_bedroom_lamp_energy
  source: sensor.master_bedroom_lamp_current_consumption
  unit_prefix: k
  round: 2

# Office Lamp
- platform: integration
  name: office_lamp_energy
  source: sensor.office_lamp_current_consumption
  unit_prefix: k
  round: 2

#-------------------#
#   -- Devices --   #
#-------------------#

# Family Room AV
- platform: integration
  name: sonoff_family_room_av_energy
  source: sensor.sonoff_family_room_av_power
  unit_prefix: k
  round: 2

# Microwave
- platform: integration
  name: sonoff_microwave_energy
  source: sensor.sonoff_microwave_power
  unit_prefix: k
  round: 2

# Refrigerator
- platform: integration
  name: sonoff_refrigerator_energy
  source: sensor.sonoff_refrigerator_power
  unit_prefix: k
  round: 2

# Treadmill
- platform: integration
  name: sonoff_treadmill_energy
  source: sensor.sonoff_treadmill_power
  unit_prefix: k
  round: 2

# Washer
- platform: integration
  name: sonoff_washer_energy
  source: sensor.sonoff_washer_power
  unit_prefix: k
  round: 2
