#=======================================#
#     Alexa Actionable Notification     #
#=======================================#

# This integrates with the Alexa custom skill AlexaActionableNotification. This skill allows us to have Alexa ask questions
# and then process the response. There are 3 parts to this process:
#
# 1) An automation or script is used to call the Activate Alexa Actionable Notification script with the message to be announced 
#    and the echo device to use. More importantly, the event ID is provided, which is used in step 3.
# 2) The Activate Alexa Actionable Notification script invokes the skill with the event ID. Alexa then asks a question and waits for a response. 
#    The skill then fires the alexa_actionable_notification event with the supplied event ID.
# 3) Automations in this file listen for the event and event ID and take whatever action is desired.

#======================#
#     Ceiling Fans     #
#======================#

# Respond to the user's fan setting request.
- alias: Alexa Handle Fan Setting Response
  id: alexa_handle_fan_setting_response
  
  trigger:
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_fan_setting_choice
        event_response_type: ResponseString
  
  action:
    - variables:
        
        # This is the set of possible settings. Turns out 'off' can't be used (tells Alexa to quit),
        # nor can 'low' (adjusts echo volume). Also, numbers ('one', 'two') do nothing. Sigh.
        # So this is what I came up with.
        fan_settings: ['fan off', 'fan low', 'fan medium', 'fan high']
        
        # This is the fan speed for each fan setting.
        fan_speeds: ['0', '33', '66', '99']
        
        # This is the response from the user.
        response_setting: "{{ trigger.event.data.event_response }}"
        
        # This is the room, saved by the Ask Fan Setting script.
        room: "{{ states('input_text.alexa_fan_room') }}"
    
    # Check for a valid response.
    - if:
        - "{{ response_setting in fan_settings }}"
      
      # All is well, set the fan!
      then:
        
        - service: script.set_fan_to_speed
          data:
            entity_id: "{{ 'fan.' ~ room ~ '_fan' }}"
            speed:  "{{ fan_speeds[fan_settings.index(response_setting)] }}"
      
      # Issue instructions to the clueless user.
      else:
        - service: script.send_notification
          data:
            destination:
              - echo
            message: "{{ response_setting }} is not valid. You must pick one of {{ (fan_settings) | join(', ') }}"
            media_player_entity: "{{ 'media_player.' ~ room ~ '_echo' }}"
