#===============================================#
#     Ecobee Thermostat Preset Mode Control     #
#===============================================#

# Ecobee climate/preset modes:
#
#   - climate_mode: This is the mode as determined by the schedule for the thermostat (first character always uppercase).
#                   For example
#                     - 'Sleep' 11:00 PM -  7:30 AM
#                     - 'Away'   7:30 AM -  5:00 PM
#                     - 'Home'   5:00 PM - 11:00 PM
#   - preset_mode:  This is normally the same value as climate_mode. But in Smart Home and Smart Away conditions,
#                   it changes to 'home' or 'away' (first character lowercase). Confusingly, it also can be 'Vacation' for
#                   a scheduled vacation, even though that value cannot be assigned as a climate or preset mode.

#===== Transition from Home to Sleep mode upstairs if the cinema is not in use =====#

# Transition to Sleep mode.
- alias: Transition To Sleep Mode
  id: transition_to_sleep_mode
  
  trigger:
    - platform: time
      at: '20:00:00'
    
    - platform: homeassistant
      event: start
  
  condition:
    - "{{ states('sensor.projector_power') | float(0) == 0 }}"
    
    - condition: state
      entity_id: input_boolean.extended_away_mode
      state: 'off'
    
    - condition: time
      after: '20:00:00'
  
  action:
    - delay: 
        seconds: "{{ range(2, 15) | random }}"
    
    - service: climate.set_preset_mode
      target:
        entity_id: climate.upstairs
      data:
        preset_mode: 'Sleep'

#============================#
#     Extended Away Mode     #
#============================#

# Triggered on the start of an extended away period.
- alias: Enable Extended Away Mode
  id: enable_extended_away_mode
  
  trigger:
    - platform: time
      at: input_datetime.extended_away_start
  
  action:
    
    # Turn on extended away mode.
    - service: input_boolean.turn_on
      entity_id: input_boolean.extended_away_mode
    
    # Set thermostat holds.
    - service: script.set_extended_thermostat_hold
      data:
        thermostat_entity: climate.downstairs
        heat_temp: !secret constant_extended_hold_heat_temp
        cool_temp: !secret constant_extended_hold_cool_temp
    
    - service: script.set_extended_thermostat_hold
      data:
        thermostat_entity: climate.upstairs
        heat_temp: !secret constant_extended_hold_heat_temp
        cool_temp: !secret constant_extended_hold_cool_temp

# Triggered on the end of an extended away period.
- alias: Disable Extended Away Mode
  id: disable_extended_away_mode
  
  trigger:
    - platform: time
      at: input_datetime.extended_away_end
  
  action:
    
    # Turn off extended away mode.
    - service: input_boolean.turn_off
      entity_id: input_boolean.extended_away_mode
    
    # Remove thermostat holds.
    - service: script.remove_thermostat_hold
      data:
        thermostat_entity: climate.downstairs
        extended: true
    
    - service: script.remove_thermostat_hold
      data:
        thermostat_entity: climate.upstairs
        extended: true

#============================================#
#     Temperature High / Low Water Marks     #
#============================================#

# Attic temperatures.
- alias: Set Minimum Attic Temperature
  id: set_minimum_attic_temperature
  use_blueprint:
    path: climate/temp_extremes.yaml
    input:
      sensor_entity: sensor.attic_temp_min
      result_entity: input_number.min_attic_temp
      type: Min

- alias: Set Maximum Attic Temperature
  id: set_maximum_attic_temperature
  use_blueprint:
    path: climate/temp_extremes.yaml
    input:
      sensor_entity: sensor.attic_temp_max
      result_entity: input_number.max_attic_temp
      type: Max

# Garage temperatures.
- alias: Set Minimum Garage Temperature
  id: set_minimum_garage_temperature
  use_blueprint:
    path: climate/temp_extremes.yaml
    input:
      sensor_entity: sensor.garage_temp_min
      result_entity: input_number.min_garage_temp
      type: Min

- alias: Set Maximum Garage Temperature
  id: set_maximum_garage_temperature
  use_blueprint:
    path: climate/temp_extremes.yaml
    input:
      sensor_entity: sensor.garage_temp_max
      result_entity: input_number.max_garage_temp
      type: Max

# Outdoor temperatures.
- alias: Set Minimum Outdoor Temperature
  id: set_minimum_outdoor_temperature
  use_blueprint:
    path: climate/temp_extremes.yaml
    input:
      sensor_entity: sensor.porch_temp_min
      result_entity: input_number.min_outdoor_temp
      type: Min

- alias: Set Maximum Outdoor Temperature
  id: set_maximum_outdoor_temperature
  use_blueprint:
    path: climate/temp_extremes.yaml
    input:
      sensor_entity: sensor.porch_temp_max
      result_entity: input_number.max_outdoor_temp
      type: Max

#=================#
#     Open UV     #
#=================#

# Update OpenUV once per hour during daylight.
- alias: Update OpenUV
  id: 'update_openuv'
  trigger:
    - platform: time_pattern
      minutes: 19
  condition:
    - condition: state
      entity_id: sun.sun
      state: above_horizon
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.current_uv_index

#========================#
#     Door & Windows     #
#========================#

# Turn off the downstairs HVAC system when any downstairs doors or windows are opened.
- alias: Turn Off Downstairs HVAC
  id: turn_off_downstairs_hvac
  
  trigger:
    - platform: state
      entity_id: group.downstairs_doors_windows
      from: 'off'
      to: 'on'
      for: '00:02:00'

  action:
    - service: climate.turn_off
      target:
        entity_id: climate.downstairs

# Turn on the downstairs HVAC system when all downstairs doors and windows are closed.
- alias: Turn On Downstairs HVAC
  id: turn_on_downstairs_hvac
  
  trigger:
    - platform: state
      entity_id: group.downstairs_doors_windows
      from: 'on'
      to: 'off'
      for: '00:02:00'

  action:
    - service: climate.turn_on
      target:
        entity_id: climate.downstairs
