#===========================#
#     Calories History      #
#===========================#

# Save the monthly calories used to maintain a history for the dashboard.
- alias: Save Monthly Calories
  id: save_monthly_calories
  
  # Trigger when the total monthly calories sensor changes.
  triggers:
    - trigger: state
      entity_id: sensor.total_monthly_calories
    
  # This should ensure we are actually changing from a valid state, and not just triggering because
  # the current value is 0, and that's it's the first day of the month.
  conditions:
    - "{{ now().day == 1 }}"
    
    - "{{ trigger.from_state and trigger.from_state.state | float(0) > 0.0 }}"
  
  # Determine the previous month using the 'from' state's last changed value.
  variables:
    value: "{{ trigger.from_state.state | float(0) }}"
    month: "{{ as_timestamp(trigger.from_state.last_changed) | timestamp_custom('%b') | lower() }}"
  
  actions:
    - action: input_number.set_value
      target:
        entity_id: "input_number.calories_{{ month }}"
      data:
        value: "{{ value }}"

#==========================#
#     Manual Exercise      #
#==========================#
    
# The companion app on Android keeps a single steps counter that just keeps increasing (yeah, rather useless). We have a utility meter
# that translates this to a daily value, but since this updates many times per day, it's not useful for keeping track of the steps as 
# an exercise metric. So each night, copy the utility meter value to an input number, which then drives the Process Steps Exercise
# automation to manage the exercise metric.
- alias: Copy Daily Steps
  id: copy_daily_steps
  
  triggers:
    - trigger: time
      at: '23:59:00'
  
  actions:
    - action: input_number.set_value
      target:
        entity_id: input_number.steps_daily
      data:
        value: "{{ states('sensor.steps_daily') }}"

# Workout exercise.
- alias: Process Workout Exercise
  id: 'process_workout_exercise'
  
  use_blueprint:
    path: health/process_exercise.yaml
    input:
      exercise_type: workout
      units_entity: input_number.workout_daily_time

# Yard work exercise.
- alias: Process Yard Work Exercise
  id: 'process_yard_work_exercise'
  
  use_blueprint:
    path: health/process_exercise.yaml
    input:
      exercise_type: yard_work
      units_entity: input_number.yard_work_daily_time

# Other exercise.
- alias: Process Other Exercise
  id: 'process_other_exercise'
  
  use_blueprint:
    path: health/process_exercise.yaml
    input:
      exercise_type: other
      units_entity: input_number.other_daily_time

# Steps exercise.
- alias: Process Steps Exercise
  id: 'process_steps_exercise'
  
  use_blueprint:
    path: health/process_exercise.yaml
    input:
      exercise_type: steps
      units_entity: input_number.steps_daily

#================#
#     Sleep      #
#================#

# Log daily sleep data for help with sleep apnea monitoring.
- alias: Log Daily Sleep Data
  id: log_daily_sleep_data

  triggers:
    
    # Trigger on the CPAP last collected sensor, which should change every day.
    - trigger: state
      entity_id: sensor.cpap_sleep_data_last_collected
      to:
  
  actions:
            
    - action: notify.send_message
      target:
        entity_id: notify.sleep_data
      data:
        message: >
          {% set date = states('sensor.cpap_current_data_date') %}
          {% set sleep_dur = states('sensor.sleep_duration_display') %}
          {% set sleep_avg = states('sensor.sleep_average_display') %}
          {% set cpap_dur = states('sensor.cpap_usage_time') %}
          {% set cpap_avg = states('sensor.cpap_average_display') %}
          {% set ahi_num = states('sensor.cpap_ahi_events_per_hour') %}
          {% set ahi_avg = states('sensor.ahi_average') %}
          {% set score = states('sensor.cpap_total_myair_score') %}
          {% set score_avg = states('sensor.cpap_score_average') %}
          {% set on_off = states('sensor.cpap_mask_on_off') %}
          {% set leak = states('sensor.cpap_mask_leak') %}
          
          {{ as_timestamp(now()) | timestamp_custom('%b %d %Y %X') ~ 
             ': Data for ' ~ date ~
             '; Sleep hours/average: ' ~ sleep_dur ~ '/' ~ sleep_avg ~ 
             '; CPAP hours/average: ' ~ cpap_dur ~ '/' ~ cpap_avg ~ 
             '; AHI number/average: ' ~ ahi_num ~ '/' ~ ahi_avg ~ 
             '; Score/average: ' ~ score ~ '/' ~ score_avg ~ 
             '; Mask on/off: ' ~ on_off ~ '; Leak: ' ~ leak ~ '%' }}
