#=====================================#
#     Nighttime / Sleeptime Modes     #
#=====================================#

# The Nighttime flag indicates I've gone to bed. The main usage is to prevent certain automations 
# (like turning on lights) from running at an inappropriate time.
#
# The Sleeptime flag covers the period from going to bed and going to sleep. Normally I'm reading,
# so don't want the bedroom light turning off unexpectedly.
#
# These flags are usually managed by the bedtime, sleeptime, awake and wakeup scripts. But if those
# are not used for some reason, also manage the flags here using failsafe times.

# Set Nighttime true at a failsafe time (should be in bed).
- alias: Enable Nighttime Mode
  id: 'enable_nighttime_mode'
  trigger:
    - platform: time
      at: '00:30:00'
    - platform: homeassistant
      event: start
  condition:
    - condition: time
      after: '00:30:00'
      before: '07:30:00'
  action:
    - delay: 
        seconds: "{{ range(2, 15) | random }}"
    - service: input_boolean.turn_on
      entity_id: input_boolean.nighttime

# Set Sleeptime true at a failsafe time (should be asleep).
- alias: Enable Sleeptime Mode
  id: 'enable_sleeptime_mode'
  trigger:
    - platform: time
      at: '01:30:00'
    - platform: homeassistant
      event: start
  condition:
    - condition: time
      after: '01:30:00'
      before: '07:30:00'
  action:
    - delay: 
        seconds: "{{ range(2, 15) | random }}"
    - service: input_boolean.turn_on
      entity_id: input_boolean.sleeptime

# Set Nighttime and Sleeptime false at a failsafe time (should be out of bed).
- alias: Disable Nighttime & Sleeptime Modes
  id: 'disable_nighttime_sleeptime_modes'
  trigger:
    - platform: time
      at: '07:30:00'
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: 2.0
    - platform: homeassistant
      event: start
  condition:
    - or:
      - condition: time
        after: '07:30:00'
        before: '23:00:00'
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        above: 2.0
  action:
    - delay: 
        seconds: "{{ range(2, 15) | random }}"
    - service: input_boolean.turn_off
      entity_id: input_boolean.nighttime
    - service: input_boolean.turn_off
      entity_id: input_boolean.sleeptime

# Reset the bedtime environment when the nighttime flag turns off.
- alias: Reset Bedtime Environment
  id: 'reset_bedtime_environment'
  
  trigger:
    - platform: state
      entity_id: input_boolean.nighttime
      from: 'on'
      to: 'off'
  
  action:
    - service: script.reset_bedtime_environment

# Set up the correct pre-bedtime environment based on the bedroom(s) to be occupied.
- alias: Set up Pre-bedtime Environment
  id: 'set_up_pre_bedtime_environment'
  
  trigger:
    - platform: state
      entity_id: input_select.occupied_bedrooms  
  
  condition:
    - condition: template
      value_template: "{{ is_state('input_boolean.adults_home', 'off') and is_state('input_boolean.children_home', 'on') }}"
  
  action:
    - service: script.set_up_pre_bedtime_environment

#===============================#
#     Change Daytime Lights     #
#===============================#

# Turn the daytime lights on or off near sunrise or sunset. This is accomplished with a set of scripts,
# and triggers when the sun elevation is somewhat near the horizon. The goals are:
#
# 1) Turn the lights on when the wakeup script is triggered and it's dark enough inside. Note that this 
#    goal is triggered by the wakeup script, not these automations, but included in this description for
#    completeness.
# 2) Turn the lights off when it becomes light enough inside after sunrise.
# 3) Turn the lights on when it becomes dark enough inside before sunset.
#
# NOTE: The elevations used here must match those in change_lighting_per_weather in script/time.yaml,
#       and in the used blueprints.

# Sunrise ...

# Check at a minimum sun elevation.
- alias: Check Daytime Lights Sunrise Minimum
  id: 'check_daytime_lights_sunrise_minimum'
  use_blueprint:
    path: lighting/sunrise_light_weather.yaml
    input:
      elevation: input_number.min_elevation
      light_entity: light.daytime_lights

# Check at a medium sun elevation.
- alias: Check Daytime Lights Sunrise Medium
  id: 'check_daytime_lights_sunrise_medium'
  use_blueprint:
    path: lighting/sunrise_light_weather.yaml
    input:
      elevation: input_number.med_elevation
      light_entity: light.daytime_lights

# Check at a maximum sun elevation.
- alias: Check Daytime Lights Sunrise Maximum
  id: 'check_daytime_lights_sunrise_maximum'
  use_blueprint:
    path: lighting/sunrise_light_weather.yaml
    input:
      elevation: input_number.max_elevation
      light_entity: light.daytime_lights

# Sunset ...

# Check at a maximum sun elevation.
- alias: Check Daytime Lights Sunset Maximum
  id: 'check_daytime_lights_sunset_maximum'
  use_blueprint:
    path: lighting/sunset_light_weather.yaml
    input:
      elevation: input_number.max_elevation
      light_entity: >
        {% if is_state('input_boolean.christmas_mode', 'off') %}
          light.daytime_lights
        {% else %}
          light.daytime_christmas_lights
        {% endif %}

# Check at a medium sun elevation.
- alias: Check Daytime Lights Sunset Medium
  id: 'check_daytime_lights_sunset_medium'
  use_blueprint:
    path: lighting/sunset_light_weather.yaml
    input:
      elevation: input_number.med_elevation
      light_entity: >
        {% if is_state('input_boolean.christmas_mode', 'off') %}
          light.daytime_lights
        {% else %}
          light.daytime_christmas_lights
        {% endif %}

# Check at a minimum sun elevation.
- alias: Check Daytime Lights Sunset Minimum
  id: 'check_daytime_lights_sunset_minimum'
  use_blueprint:
    path: lighting/sunset_light_weather.yaml
    input:
      elevation: input_number.min_elevation
      light_entity: >
        {% if is_state('input_boolean.christmas_mode', 'off') %}
          light.daytime_lights
        {% else %}
          light.daytime_christmas_lights
        {% endif %}

#======================#
#     Lux Sensors      #
#======================#

# Turn on office light based on ambient lux level.
- alias: Turn On Office Light
  id: 'turn_on_office_light'
  trigger:
    - platform: numeric_state
      entity_id: sensor.office_ambient_light
      below: 150
      for: '00:02:00'
    - platform: state
      entity_id: input_boolean.nighttime
      from: 'on'
      to: 'off'
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: input_boolean.nighttime
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.office_ambient_light
      below: 150
    - condition: state
      entity_id: input_boolean.extended_away_mode
      state: 'off'
  action:
    - delay: 
        seconds: "{{ range(2, 15) | random }}"
    - service: light.turn_on
      entity_id: light.office_lamp

# Turn off office light based on ambient lux level.
- alias: Turn Off Office Light
  id: 'turn_off_office_light'
  trigger:
    - platform: numeric_state
      entity_id: sensor.office_ambient_light
      above: 300
      for: '00:02:00'
    - platform: homeassistant
      event: start
  condition:
    - condition: numeric_state
      entity_id: sensor.office_ambient_light
      above: 300
  action:
    - delay: 
        seconds: "{{ range(2, 15) | random }}"
    - service: light.turn_off
      entity_id: light.office_lamp

#==============================#
#     Extended Away Lights     #
#==============================#

# Randomly turn certain lights on/off during extended away mode, between ~sunset and nighttime start, and
# between nighttime end and ~sunrise (only occurs during winter-ish months).

- alias: Run Extended Away Lights
  id: run_extended_away_lights
  trigger:
    - platform: state
      entity_id: input_boolean.extended_away_mode
      to: 'on'
    - platform: state
      entity_id: input_boolean.nighttime
      to: 'off'
    - platform: state
      entity_id: sun.sun
      to: below_horizon
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: input_boolean.extended_away_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.nighttime
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: below_horizon
  action:
    - delay: 
        seconds: "{{ range(2, 15) | random }}"
    
    # The script randomly toggles lights in the away group until the above conditions are
    # no longer met. We wait here until that happens.
    - service: script.automate_lights_while_away
    
    # The conditions are no longer true, so turn off all of the away lights.
    - service: homeassistant.turn_off
      entity_id: light.away_lights

#=========================#
#     Motion Sensors      #
#=========================#

- alias: Run Guest Bath Motion Based Light
  id: 'run_guest_bath_motion_based_light'
  use_blueprint:
    path: lighting/motion_light_with_fan.yaml
    input:
      motion_entity: binary_sensor.guest_bath_motion_detector_occupancy
      light_entity: light.guest_bath_light
      fan_entity: switch.guest_bath_fan
      no_motion_wait_fan_off: 120
      no_motion_wait_fan_on:  420
      additional_fan_wait:    300
      windowed: false

- alias: Run Laundry Room Motion Based Light
  id: 'run_laundry_room_motion_based_light'
  use_blueprint:
    path: lighting/motion_light.yaml
    input:
      motion_entity: binary_sensor.laundry_room_motion_detector_occupancy
      light_target: 
        entity_id: light.laundry_room_light
      no_motion_wait: 180

- alias: Run Master Bath Motion Based Light
  id: 'run_master_bath_motion_based_light'
  use_blueprint:
    path: lighting/motion_light_with_fan.yaml
    input:
      motion_entity: binary_sensor.master_bath_motion_detector_occupancy
      light_entity: light.master_bath_light
      fan_entity: switch.master_bath_fan
      no_motion_wait_fan_off: 240
      no_motion_wait_fan_on:  420
      additional_fan_wait:    300
      windowed: true

#======================#
#     Guest Lights     #
#======================#

# Turn off guest lights when grandchildren leave home.
- alias: Turn Off Guest Lights
  id: 'turn_off_guest_lights'
  trigger:
    - platform: state
      entity_id: input_boolean.children_home
      to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.guest_bedroom_lamp_2

# Turn on guest lights near sunset when grandchildren arrive or are already home.
- alias: Turn On Guest Lights Sunset
  id: 'turn_on_guest_lights_sunset'
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 4.0
    - platform: state
      entity_id: input_boolean.children_home
      to: 'on'
    - platform: homeassistant
      event: start
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 4.0
    - condition: state
      entity_id: input_boolean.children_home
      state: 'on'
    - condition: state
      entity_id: input_boolean.nighttime
      state: 'off'
  action:
    - delay: 
        seconds: "{{ range(2, 15) | random }}"
    - choose:
      - conditions:
        - condition: state
          entity_id: input_select.occupied_bedrooms
          state: 'Master'
        sequence:
          - service: light.turn_on
            entity_id: light.master_bedroom_lamp
      default:
        - service: light.turn_on
          entity_id: light.guest_bedroom_lamp_2

# Turn off guest bedroom lights after bedtime when grandchildren are home.
- alias: Turn Off Guest Bedroom Lights Bedtime
  id: 'turn_off_guest_bedroom_lights_bedtime'
  trigger:
    - platform: time
      at: '22:30:00'
    - platform: homeassistant
      event: start
  condition:
    - condition: time
      after: '22:30:00'
    - condition: template
      value_template: "{{ not is_state('person.sarah', 'home') and is_state('input_boolean.children_home', 'on') }}"
  action:
    - delay: 
        seconds: "{{ range(2, 15) | random }}"
    - service: light.turn_off
      entity_id: light.guest_bedroom_lamp
    - service: light.turn_off
      entity_id: light.guest_bedroom_lamp_2

#==========================#
#     Christmas Lights     #
#==========================#

# Turn on Christmas lights in the morning on certain Christmas-y days.
- alias: Turn On Christmas Lights
  id: 'turn_on_christmas_lights'
  trigger:
    - platform: time
      at: '08:00:00'
    - platform: homeassistant
      event: start
  condition:
    - condition: time
      after: '08:00:00'
    - condition: time
      before: '22:00:00'
    - condition: state
      entity_id: person.jon
      state: 'home'
    - condition: template
      value_template: >
        {{ now().strftime('%m-%d') == '12-24' or
           now().strftime('%m-%d') == '12-25' or
           now().strftime('%m-%d') == '12-26' or
           now().strftime('%m-%d') == '12-31' or
           now().strftime('%m-%d') == '01-01' }}
  action:
    - delay: 
        seconds: "{{ range(2, 15) | random }}"
    - service: script.turn_on_christmas_lights

# Turn off Christmas lights at night on certain Christmas-y days.
- alias: Turn Off Christmas Lights
  id: 'turn_off_christmas_lights'
  trigger:
    - platform: time
      at: '22:00:00'
    - platform: homeassistant
      event: start
  condition:
    - condition: time
      after: '22:00:00'
    - condition: time
      before: '08:00:00'
    - condition: template
      value_template: >
        {{ now().strftime('%m-%d') == '12-24' or
           now().strftime('%m-%d') == '12-25' or
           now().strftime('%m-%d') == '12-26' or
           now().strftime('%m-%d') == '12-31' or
           now().strftime('%m-%d') == '01-01' }}
  action:
    - delay: 
        seconds: "{{ range(2, 15) | random }}"
    - service: script.turn_off_christmas_lights

#=====================#
#     Smart Bulbs     #
#=====================#

# Reset smart bulbs if a possible power glitch occurred. Note that catching such glitches is not guaranteed.
- alias: Reset Smart Bulbs On Power Glitch
  id: 'reset_smart_bulbs_on_power_glitch'
  trigger:
    - platform: state
      entity_id: input_boolean.possible_power_glitch
      to: 'on'
  
  action:
    - delay: '00:01:00'
    - service: script.reset_smart_bulbs
    - service: input_boolean.turn_off
      entity_id: input_boolean.possible_power_glitch
