#================================#
#     Testing Infrastructure     #
#================================#

# The idea here is to be able to simulate various states, events and what-not so I can test
# new automations/scripts that require things I can't force to happen. For example, I can't change a 
# normal device tracker to force a person to change from away to home. But I can create a test device tracker
# using MQTT, and use a UI button to control it. 

#=========================#
#     Device Trackers     #
#=========================#

# Toggle virtual device trackers.
- alias: Toggle Virtual Device Tracker
  id: 'toggle_virtual_device_tracker'
  mode: queued
  
  trigger:
    - platform: state
      entity_id:
        - input_boolean.virtual_david
        - input_boolean.virtual_maryam
        - input_boolean.virtual_mike
        - input_boolean.virtual_sarah
        - input_boolean.virtual_skylar
      to:
  
  action:
    - variables:
        new_state: >
          {% if trigger.to_state.state == 'on' %}
            home
          {% else %}
            not_home
          {% endif %}
        
        topic_suffix: "{{ trigger.to_state.entity_id | replace('input_boolean.', '') }}"
    
    - service: mqtt.publish
      data:
        topic: "{{ 'homeassistant/device_tracker/' ~ topic_suffix }}"
        payload: "{{ new_state }}"
