- alias: Test Automation
  trigger:
    - platform: time
      at: '10:37:00'
  condition:
    - condition: time
      after: '10:37:00'
  action:
    - service: light.turn_on
      entity_id: light.office_lamp