#======================#
#     Generic Test     #
#======================#

- alias: Test Automation
  trigger:
    - platform: time
      at: '10:37:00'
  condition:
    - condition: time
      after: '10:37:00'
  action:
    - service: light.turn_on
      entity_id: light.office_lamp

#=========================#
#     Temporary Tests     #
#=========================#

# Wait for result from Test Kodi script
- alias: Test Kodi Result
  mode: parallel
  trigger:
    - platform: event
      event_type: kodi_call_method_result
      event_data:
        result_ok: true
        input:
          method: VideoLibrary.GetMusicVideos
  action:
  - delay:
      milliseconds: 500
  - event: test_kodi_result
    event_data:
      source: "{{ trigger.event.data.entity_id }}"
      result: "{{ trigger.event.data.result }}"

# Log context for device trackers
- alias: Log Tracker Context
  
  trigger:
    - platform: state
      entity_id:
        - device_tracker.life360_jon_franks
        - device_tracker.jon_galaxy
  
  action:
    - choose:
      
      # Life360 tracker
      - conditions:
        - condition: template
          value_template: "{{ trigger.to_state.attributes.friendly_name == 'Jon Franks' }}"
        sequence:
          - condition: template
            value_template: >
              {{ 
                 trigger.from_state.attributes.battery_level == trigger.to_state.attributes.battery_level and
                 trigger.from_state.attributes.latitude == trigger.to_state.attributes.latitude and
                 trigger.from_state.attributes.longitude == trigger.to_state.attributes.longitude and
                 trigger.from_state.attributes.gps_accuracy == trigger.to_state.attributes.gps_accuracy and
                 trigger.from_state.attributes.address == trigger.to_state.attributes.address and
                 trigger.from_state.attributes.at_loc_since == trigger.to_state.attributes.at_loc_since and
                 trigger.from_state.attributes.battery_charging == trigger.to_state.attributes.battery_charging and
                 trigger.from_state.attributes.driving == trigger.to_state.attributes.driving and
                 trigger.from_state.attributes.last_seen == trigger.to_state.attributes.last_seen and
                 trigger.from_state.attributes.place == trigger.to_state.attributes.place and
                 trigger.from_state.attributes.speed == trigger.to_state.attributes.speed and
                 trigger.from_state.attributes.wifi_on == trigger.to_state.attributes.wifi_on
              }}
          
          - service: system_log.write
            data:
              message: "JKF: {{ trigger.from_state.attributes.friendly_name }}({{ trigger.from_state.state }}) From Context: {{ trigger.from_state.context.id }}, parent ID: {{ trigger.from_state.context.parent_id }}, user ID: {{ trigger.from_state.context.user_id }}, Atts: {{ trigger.from_state.attributes }}"
              level: info
          - service: system_log.write
            data:
              message: "JKF: {{ trigger.to_state.attributes.friendly_name }}({{ trigger.to_state.state }}) To   Context: {{ trigger.to_state.context.id }}, parent ID: {{ trigger.to_state.context.parent_id }}, user ID: {{ trigger.to_state.context.user_id }}, Atts: {{ trigger.to_state.attributes }}"
              level: info
      
      # HA on phone tracker
      - conditions:
        - condition: template
          value_template: "{{ trigger.to_state.attributes.friendly_name == 'Jon-Galaxy' }}"
        sequence:
          - condition: template
            value_template: >
              {{ 
                 trigger.from_state.attributes.latitude == trigger.to_state.attributes.latitude and
                 trigger.from_state.attributes.longitude == trigger.to_state.attributes.longitude and
                 trigger.from_state.attributes.gps_accuracy == trigger.to_state.attributes.gps_accuracy and
                 trigger.from_state.attributes.altitude == trigger.to_state.attributes.altitude and
                 trigger.from_state.attributes.course == trigger.to_state.attributes.course and
                 trigger.from_state.attributes.speed == trigger.to_state.attributes.speed and
                 trigger.from_state.attributes.vertical_accuracy == trigger.to_state.attributes.vertical_accuracy
              }}
          
          - service: system_log.write
            data:
              message: "JKF: {{ trigger.from_state.attributes.friendly_name }}({{ trigger.from_state.state }}) From Context: {{ trigger.from_state.context.id }}, parent ID: {{ trigger.from_state.context.parent_id }}, user ID: {{ trigger.from_state.context.user_id }}, Atts: {{ trigger.from_state.attributes }}"
              level: info
          - service: system_log.write
            data:
              message: "JKF: {{ trigger.to_state.attributes.friendly_name }}({{ trigger.to_state.state }}) To   Context: {{ trigger.to_state.context.id }}, parent ID: {{ trigger.to_state.context.parent_id }}, user ID: {{ trigger.to_state.context.user_id }}, Atts: {{ trigger.to_state.attributes }}"
              level: info
