#======================#
#     Generic Test     #
#======================#

- alias: Test Automation
  trigger:
    - platform: time
      at: '10:37:00'
  condition:
    - condition: time
      after: '10:37:00'
  action:
    - service: light.turn_on
      entity_id: light.office_lamp

#=========================#
#     Temporary Tests     #
#=========================#

# Wait for result from Test Kodi script
- alias: Test Kodi Result
  mode: parallel
  trigger:
    - platform: event
      event_type: kodi_call_method_result
      event_data:
        result_ok: true
        input:
          method: VideoLibrary.GetMusicVideos
  action:
  - delay:
      milliseconds: 500
          
  - variables:
      
      # Random index into the list of videos.
      number_of_videos: "{{ trigger.event.data.result.limits.total }}"
      index: "{{ range(0, number_of_videos - 1) | random }}"
  - service: system_log.write
    data:
      message: "JKF: total {{number_of_videos}}, index {{index}}"
      level: info
          
  - variables:
      
      # Data from the randomly selected video.
      artist: >
        {% set artist_str = 'trigger.event.data.result.musicvideos.' ~ index ~ '.artist.0' %}
        {{ artist_str }}
      videoid: "{{ trigger.event.data.result.musicvideos.10.musicvideoid }}"
      runtime: "{{ trigger.event.data.result.musicvideos.10.streamdetails.video.0.duration }}"
  - service: system_log.write
    data:
      message: "JKF: artist {{artist}}, ID {{videoid}}, runtime {{runtime}}"
      level: info

#==============#
#     Kodi     #
#==============#
  
- alias: Test Kodi Result Event
  id: test_kodi_result_event
  
  trigger:
    - platform: event
      event_type: kodi_call_method_result
      event_data:
        result_ok: true
        input:
          method: VideoLibrary.GetMovies
        
  action:
    - service: system_log.write
      data:
        message: "JKF: {{ trigger.event.data }}"
        level: warning

#=======================================#
#     Alexa Actionable Notification     #
#=======================================#

- alias: Test Alexa Actionable Notification
  id: test_alexa_actionable_notification
  
  trigger:
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: actionable_notification_flash_light
        event_response_type: ResponseYes
  
  action:
    - service: script.test_light_flash
