# Device specific information
substitutions:
  friendly_name:   Downstairs Sensor
  
  # Used by boards
  device_name:     downstairs-sensor
  loglevel:        DEBUG
  
  # Used by WiFi
  update_interval: 600s
  
  # Used by sensors
  window_interval: 60s
  
  # Used by TSL2591 sensor
  gain:            high

# Pull in common configuration
packages:
  esp32_base:     !include common/esp32_base.yaml
  wifi:           !include common/wifi.yaml
  tsl2591_sensor: !include common/tsl2591_sensor.yaml

# Enable Home Assistant API
api:

# Enable I2C, needed for the TSL2591 sensor
i2c:
  sda: 21
  scl: 22
  scan: True
