# Device specific information
substitutions:
  friendly_name:      Dryer Sensor
  
  # Used by boards
  device_name:        dryer-sensor
  loglevel:           DEBUG
  
  # Used by WiFi
  update_interval:    60s
  
  # Used by sensors
  window_interval:    5s
  window_size:        "1"
  
  # Used by temperature sensors
  calibrate_measured: "72.0"
  calibrate_truth:    "72.0"

# Pull in common configuration
packages:
  nodemcu_base:       !include common/nodemcu_base.yaml
  wifi:               !include common/wifi.yaml
  dht_sensor:         !include common/dht_sensor.yaml
  gpio_binary_sensor: !include common/gpio_binary_sensor.yaml

# Enable Home Assistant API
api:
