# NOTE: This configuration is from the ESPHome pre-built bluetooth proxy. The only thing I changed is to
# pull in my personal wifi include.
substitutions:  
  name: esp32-bluetooth-proxy
  friendly_name: Bluetooth Proxy
  update_interval: 600s

packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main
  wifi: !include common/wifi.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: TC7+FsahLXineIwEPiWbRGw5Nhm0G6ncKvme/95yvbM=
