substitutions:
  name: esp32-bluetooth-proxy-a86944
  friendly_name: Bluetooth Proxy 1
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 4zwnma76AEgfRo24gVWNYcvM9zS/lGAxc4OQpE0bQuk=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
