substitutions:
  name: "family-room-box3"
  friendly_name: Family Room Box3
packages:
  esphome.voice-assistant: github://esphome/wake-word-voice-assistants/esp32-s3-box-3/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: ev/3zwooOVV6Is40GReX1+b62C38AjilfGx+4ggjtPM=

esp32:
  board: esp32s3box
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
