substitutions:
  name: "family-room-box3"
  friendly_name: Family Room Box3
packages:
  esphome.voice-assistant: github://esphome/wake-word-voice-assistants/esp32-s3-box-3/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 4TTpKBkk6oPPWE/uoBznGvCo7f0k1SvFXIwLpsfo3x4=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
