substitutions:
  name: "family-room-box3"
  friendly_name: Family Room Box3
packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: nzdScfHqqlzhKdzk3i4oxhVXZRFHbqXIetKIkhR1s/Q=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password    
