# Device specific information
substitutions:
  friendly_name:             Porch Sensor
  
  # Used by boards (device name also used by MQTT)
  device_name:               porch-sensor
  loglevel:                  DEBUG
  
  # Used by WiFi
  update_interval:           3s
  
  # Used by sensors
  window_interval:           3s
  window_size:               "1"
  
  # Used by temperature sensors
  calibrate_measured:        "72.0"
  calibrate_truth:           "72.0"
  
  # Used by humidity sensors
  hum_calibrate_measured_1:  "85.0"
  hum_calibrate_truth_1:     "75.0"
  hum_calibrate_measured_2:  "74.0"
  hum_calibrate_truth_2:     "66.0"
  hum_calibrate_measured_3:  "64.0"
  hum_calibrate_truth_3:     "60.0"
  hum_calibrate_measured_4:  "50.0"
  hum_calibrate_truth_4:     "50.0"
  
  # Used by bme280 sensor
  prefix:                    porch_sensor

# Pull in common configuration
packages:
  d1mini_base:    !include common/d1mini_base.yaml
  wifi:           !include common/wifi.yaml
  bme280_sensor:  !include common/bme280_sensor.yaml
  mqtt:           !include common/mqtt.yaml

# MQTT - we use MQTT instead of the Home Assistant API because we utilize deep sleep
mqtt:
  on_message: 
    - topic: ${device_name}/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_control
        - logger.log: "Deep Sleep Suspended"
    - topic: ${device_name}/ota_mode
      payload: 'OFF'
      then:
        - logger.log: "Deep Sleep Resumed"
        - deep_sleep.enter: deep_sleep_control

# Deep sleep
deep_sleep:
  id: deep_sleep_control
  run_duration:   5s
  sleep_duration: 595s

# Enable I2C, needed for the BME280 sensor
i2c:
  sda: D2
  scl: D1
  scan: True

# Sensors
sensor:

  # Battery level sensor
  - platform: adc
    pin: A0
    id: "LIION"
    update_interval: $update_interval
    accuracy_decimals: 3
    filters:
      - multiply: 4.2  
  
  - platform: template
    name: Battery Voltage
    unit_of_measurement: 'V'
    icon: "mdi:battery-plus"
    update_interval: $update_interval
    accuracy_decimals: 2
    lambda: |-
      return (id(LIION).state);
    
  - platform: template
    name: Battery Level
    unit_of_measurement: '%'
    icon: "mdi:battery-medium"
    update_interval: $update_interval
    accuracy_decimals: 1
    lambda: |-
      return ((id(LIION).state-3) /1.2 * 100.00);
